services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  
    environment:
      - POSTGRES_DB=mysterymaze
      - POSTGRES_USER=chaiaurcode
      - POSTGRES_PASSWORD=chaiaurcode

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # backend:
  #   image: backend24
  #   container_name: backend
  #   environment:
  #     DATABASE_URL: postgresql://chaiaurcode:chaiaurcode@db:5432/mysterymaze
  #   depends_on:
  #     - db
  #   ports:
  #     - "4000:4000"

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
